In [196]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import jaccard_score, plot_confusion_matrix
from sklearn.preprocessing import StandardScaler

In [74]:
df1 = pd.read_csv('train_set.csv')
df2 = pd.read_csv('train_NDVI_misra_b5.csv')

In [75]:
df2 = df2.drop(columns=['years', 'crop_type'])

In [76]:
df1

evi_avg_1  evi_std_1  evi_max_1  evi_min_1  evi_avg_2  evi_std_2  \
0      0.517812   0.101451   0.824661   0.237408   0.247882   0.040427   
1      0.435911   0.104245   0.812585   0.322871   0.405477   0.042267   
2      0.622497   0.186751   0.996448   0.352356   0.384047   0.092514   
3      0.586952   0.147604   1.000143   0.374724   0.542560   0.125139   
4      0.642429   0.165903   0.965823   0.269221   0.614477   0.160949   
...         ...        ...        ...        ...        ...        ...   
1312   0.708120   0.101001   1.061685   0.503407   0.614711   0.120282   
1313   0.520192   0.030040   0.586495   0.427981   0.503780   0.041044   
1314   0.508603   0.084394   0.747615   0.331204   0.427727   0.150579   
1315   0.566512   0.209918   1.044079   0.231355   0.449323   0.164601   
1316   0.469706   0.201024   0.961102   0.207788   0.381935   0.190351   

      evi_max_2  evi_min_2  evi_avg_3  evi_std_3  ...  m_5  m_6  m_7  m_8  \
0      0.438997   0.209346   0.274252   0.060674  ...    5    9    5    4   
1      0.583946   0.320958   0.493523   0.044502  ...    4    4    4    4   
2      0.737913   0.233535   0.364407   0.145277  ...    4    4    4    4   
3      0.893775   0.307429   0.470813   0.287797  ...    4    4    4    4   
4      0.984423   0.113945   0.584061   0.126444  ...    5    5    5    4   
...         ...        ...        ...        ...  ...  ...  ...  ...  ...   
1312   1.003045   0.309150   0.596270   0.087906  ...    4    5    5    4   
1313   0.593947   0.369326   0.787472   0.110260  ...    5    7    5    5   
1314   0.857926   0.230881   0.392108   0.084875  ...    4    4    5    4   
1315   0.899381   0.187217   0.414475   0.218072  ...    4    4    5    4   
1316   0.957979   0.206951   0.374935   0.182342  ...    4    4    4    4   

      m_9  m_10  m_11  m_12  crop_type  years  
0       7     4     4     4          1   2021  
1       4     4     4     5          1   2021  
2       4     4     4     4          1   2021  
3       4     9     4     4          3   2021  
4       6     5     5     5          2   2021  
...   ...   ...   ...   ...        ...    ...  
1312    4     4     4     4          3   2021  
1313    6     4     4     4          3   2021  
1314    4     4     4     5          1   2021  
1315    4     9     4     5          3   2021  
1316    4     4     4     4          3   2021  

[1317 rows x 206 columns]

In [77]:
df2

ndvi_avg_1  ndvi_std_1  ndvi_max_1  ndvi_min_1  ndvi_avg_2  ndvi_std_2  \
0       0.362654    0.071053    0.577553    0.166265    0.362654    0.071053   
1       0.305288    0.073008    0.569094    0.226119    0.305288    0.073008   
2       0.435967    0.130793    0.697862    0.246769    0.435967    0.130793   
3       0.411076    0.103376    0.700456    0.262450    0.411076    0.103376   
4       0.449940    0.116193    0.676429    0.188548    0.449940    0.116193   
...          ...         ...         ...         ...         ...         ...   
1312    0.495934    0.070735    0.743562    0.352560    0.495934    0.070735   
1313    0.364318    0.021039    0.410750    0.299737    0.364318    0.021039   
1314    0.356196    0.059106    0.523591    0.231957    0.356196    0.059106   
1315    0.396760    0.147018    0.731215    0.162031    0.396760    0.147018   
1316    0.328962    0.140793    0.673118    0.145522    0.328962    0.140793   

      ndvi_max_2  ndvi_min_2  ndvi_avg_3  ndvi_std_3  ...  b5_max_10  \
0       0.577553    0.166265    0.173601    0.028314  ...     1748.0   
1       0.569094    0.226119    0.283975    0.029603  ...     2559.0   
2       0.697862    0.246769    0.268968    0.064795  ...     2132.0   
3       0.700456    0.262450    0.379986    0.087642  ...     2035.0   
4       0.676429    0.188548    0.430359    0.112723  ...     3568.0   
...          ...         ...         ...         ...  ...        ...   
1312    0.743562    0.352560    0.430522    0.084240  ...     1284.0   
1313    0.410750    0.299737    0.352829    0.028747  ...     1362.0   
1314    0.523591    0.231957    0.299553    0.105460  ...     3067.0   
1315    0.731215    0.162031    0.314686    0.115279  ...     1053.0   
1316    0.673118    0.145522    0.267491    0.133320  ...     1944.0   

      b5_min_10    b5_avg_11   b5_std_11  b5_max_11  b5_min_11    b5_avg_12  \
0         899.0  1510.853333  232.963384     2278.0      643.0  3319.880000   
1        1400.0  2289.415385  422.435134     2996.0     1177.0  2337.192308   
2        1307.0  1012.100000  257.338372     1580.0      455.0  1265.611905   
3        1555.0  1004.511905  384.714999     1470.0      451.0  1733.345238   
4         842.0  1411.600000  227.893233     1988.0      649.0  1459.835714   
...         ...          ...         ...        ...        ...          ...   
1312      667.0  1689.290155  168.437897     1989.0     1115.0  1726.072539   
1313      483.0  1540.529412   88.282157     1686.0     1212.0  2225.098039   
1314     1581.0  1994.164706  395.204499     2470.0     1013.0  1976.100000   
1315      319.0   986.087179  357.731195     1859.0      490.0  1545.558974   
1316      855.0  1368.850575  322.427973     2372.0      563.0  1593.632184   

       b5_std_12  b5_max_12  b5_min_12  
0     597.459844     3756.0     1710.0  
1     392.915789     2783.0     1273.0  
2     384.454895     2279.0      798.0  
3     222.536647     2294.0     1400.0  
4     399.062090     2810.0      324.0  
...          ...        ...        ...  
1312  141.334810     1952.0     1139.0  
1313  116.788774     2423.0     2065.0  
1314  187.650039     2327.0     1485.0  
1315  302.003584     2745.0      970.0  
1316  293.548084     2334.0      730.0  

[1317 rows x 144 columns]

In [108]:
df = pd.concat([df1, df2], axis=1)
df

evi_avg_1  evi_std_1  evi_max_1  evi_min_1  evi_avg_2  evi_std_2  \
0      0.517812   0.101451   0.824661   0.237408   0.247882   0.040427   
1      0.435911   0.104245   0.812585   0.322871   0.405477   0.042267   
2      0.622497   0.186751   0.996448   0.352356   0.384047   0.092514   
3      0.586952   0.147604   1.000143   0.374724   0.542560   0.125139   
4      0.642429   0.165903   0.965823   0.269221   0.614477   0.160949   
...         ...        ...        ...        ...        ...        ...   
1312   0.708120   0.101001   1.061685   0.503407   0.614711   0.120282   
1313   0.520192   0.030040   0.586495   0.427981   0.503780   0.041044   
1314   0.508603   0.084394   0.747615   0.331204   0.427727   0.150579   
1315   0.566512   0.209918   1.044079   0.231355   0.449323   0.164601   
1316   0.469706   0.201024   0.961102   0.207788   0.381935   0.190351   

      evi_max_2  evi_min_2  evi_avg_3  evi_std_3  ...  b5_max_10  b5_min_10  \
0      0.438997   0.209346   0.274252   0.060674  ...     1748.0      899.0   
1      0.583946   0.320958   0.493523   0.044502  ...     2559.0     1400.0   
2      0.737913   0.233535   0.364407   0.145277  ...     2132.0     1307.0   
3      0.893775   0.307429   0.470813   0.287797  ...     2035.0     1555.0   
4      0.984423   0.113945   0.584061   0.126444  ...     3568.0      842.0   
...         ...        ...        ...        ...  ...        ...        ...   
1312   1.003045   0.309150   0.596270   0.087906  ...     1284.0      667.0   
1313   0.593947   0.369326   0.787472   0.110260  ...     1362.0      483.0   
1314   0.857926   0.230881   0.392108   0.084875  ...     3067.0     1581.0   
1315   0.899381   0.187217   0.414475   0.218072  ...     1053.0      319.0   
1316   0.957979   0.206951   0.374935   0.182342  ...     1944.0      855.0   

        b5_avg_11   b5_std_11  b5_max_11  b5_min_11    b5_avg_12   b5_std_12  \
0     1510.853333  232.963384     2278.0      643.0  3319.880000  597.459844   
1     2289.415385  422.435134     2996.0     1177.0  2337.192308  392.915789   
2     1012.100000  257.338372     1580.0      455.0  1265.611905  384.454895   
3     1004.511905  384.714999     1470.0      451.0  1733.345238  222.536647   
4     1411.600000  227.893233     1988.0      649.0  1459.835714  399.062090   
...           ...         ...        ...        ...          ...         ...   
1312  1689.290155  168.437897     1989.0     1115.0  1726.072539  141.334810   
1313  1540.529412   88.282157     1686.0     1212.0  2225.098039  116.788774   
1314  1994.164706  395.204499     2470.0     1013.0  1976.100000  187.650039   
1315   986.087179  357.731195     1859.0      490.0  1545.558974  302.003584   
1316  1368.850575  322.427973     2372.0      563.0  1593.632184  293.548084   

      b5_max_12  b5_min_12  
0        3756.0     1710.0  
1        2783.0     1273.0  
2        2279.0      798.0  
3        2294.0     1400.0  
4        2810.0      324.0  
...         ...        ...  
1312     1952.0     1139.0  
1313     2423.0     2065.0  
1314     2327.0     1485.0  
1315     2745.0      970.0  
1316     2334.0      730.0  

[1317 rows x 350 columns]

In [94]:
# df = df1

In [154]:
X = df.loc[:, (df.columns != 'crop_type') & (df.columns != 'years')].to_numpy()
Y = df.crop_type.to_numpy()
X.shape, Y.shape

((1317, 348), (1317,))

In [155]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [156]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [176]:
# clf1 = XGBClassifier(grow_policy='lossguide')
# clf1 = XGBClassifier(seed=seed, eta=0.02, n_estimators=225, max_depth=5, subsample=1, gamma=0.01, grow_policy='lossguide')
clf1 = XGBClassifier(seed=seed, eta=0.01, n_estimators=250, max_depth=5, subsample=1, gamma=0.01)
clf2 = RandomForestClassifier(n_estimators=50, random_state=seed)
clf3 = GaussianNB()
clf4 = LinearDiscriminantAnalysis()
clf5 = KNeighborsClassifier(n_neighbors=7)
# clf6 = MLPClassifier(random_state=seed, hidden_layer_sizes=(256,), max_iter=300)
eclf1 = VotingClassifier(estimators=[
    ('xgb', clf1), ('rf', clf2), ('gnb', clf3), ('lda', clf4), ('knn', clf5)#, ('mlp', clf6)
], voting='soft')
eclf1 = eclf1.fit(X_train_scaled, y_train)

In [177]:
y_train_pred = eclf1.predict(X_train_scaled)
y_test_pred = eclf1.predict(X_test_scaled)

In [178]:
# clf1.fit(X_train_scaled, y_train)
# y_test_pred = clf1.predict(X_test_scaled)

In [179]:
# print(np.unique(y_test_pred, return_counts=True))

print(classification_report(y_test, y_test_pred))
j_train = jaccard_score(y_train, y_train_pred, average=None)
j_test = jaccard_score(y_test, y_test_pred, average=None)
print('Jaccard train', j_train)
print('Jaccard test', j_test)
print(np.mean(j_test))
print(np.std(j_test))

(array([1, 2, 3, 4]), array([119,  51,  70,  24]))
              precision    recall  f1-score   support

           1       0.71      0.86      0.78        99
           2       0.69      0.78      0.73        45
           3       0.80      0.68      0.74        82
           4       0.79      0.50      0.61        38

    accuracy                           0.74       264
   macro avg       0.75      0.70      0.71       264
weighted avg       0.75      0.74      0.73       264

Jaccard train [0.87358916 0.8358209  0.8671875  0.72727273]
Jaccard test [0.63909774 0.57377049 0.58333333 0.44186047]
0.5595155086534483
0.07236458876241479


In [180]:
np.unique(eclf1.predict(X_train_scaled), return_counts=True)

(array([1, 2, 3, 4]), array([419, 174, 366,  94]))

In [181]:
np.unique(eclf1.predict(X_test_scaled), return_counts=True)

(array([1, 2, 3, 4]), array([119,  51,  70,  24]))

In [200]:
y_test.shape, y_test_pred.shape

((264,), (264,))

In [186]:
submit_df1 = pd.read_csv('submit_non_pred_1.csv')
submit_df2 = pd.read_csv('test_NDVI_misra_b5.csv')
submit_df2 = submit_df2.drop(columns=['years'])

submit_df = pd.concat([submit_df1, submit_df2], axis=1)
submit_df

evi_avg_1  evi_std_1  evi_max_1  evi_min_1  evi_avg_2  evi_std_2  \
0     0.383904   0.090322   0.717213   0.219532   0.326785   0.086075   
1     0.571055   0.150898   0.893476   0.314724   0.729798   0.194761   
2     0.897027   0.147680   1.092996   0.562722   0.630020   0.211884   
3     0.436343   0.110784   0.833865   0.306420   0.421935   0.105614   
4     0.318493   0.037816   0.424132   0.269871   0.308681   0.044096   
..         ...        ...        ...        ...        ...        ...   
560   0.382187   0.125087   1.012716   0.239281   0.313081   0.092251   
561   0.579013   0.137216   1.115283   0.376668   0.524856   0.123964   
562   0.325645   0.067978   0.686624   0.254590   0.309039   0.062968   
563   0.253298   0.038699   0.407235   0.212041   0.226347   0.035134   
564   0.381751   0.154736   0.889979   0.203871   0.461780   0.119135   

     evi_max_2  evi_min_2  evi_avg_3  evi_std_3  ...  b5_max_10  b5_min_10  \
0     0.634771   0.194826   0.309159   0.084846  ...     2372.0      921.0   
1     1.002523   0.212478   0.827140   0.197858  ...     1573.0      900.0   
2     0.917939   0.260840   0.344951   0.056407  ...     1639.0     1087.0   
3     0.827441   0.306043   0.548595   0.076820  ...     1199.0      940.0   
4     0.437885   0.251892   0.336574   0.070412  ...     2874.0     1910.0   
..         ...        ...        ...        ...  ...        ...        ...   
560   0.753183   0.211912   0.319574   0.139426  ...     1564.0      727.0   
561   1.007758   0.315816   0.547430   0.137089  ...     1900.0      859.0   
562   0.689306   0.244440   0.305057   0.061017  ...     4773.0     1868.0   
563   0.364615   0.183611   0.223270   0.048024  ...     2649.0     1257.0   
564   0.858603   0.206884   0.354371   0.105963  ...     4735.0      834.0   

       b5_avg_11   b5_std_11  b5_max_11  b5_min_11    b5_avg_12   b5_std_12  \
0    1252.993548  285.875373     1661.0      310.0  1486.677419  324.038686   
1    1503.625000  227.146944     2189.0     1078.0  2058.732143  458.514196   
2    1209.555556  136.898088     1997.0     1092.0  1388.851852   97.380520   
3    1122.166667  171.414891     2030.0      936.0  2126.296296  319.600539   
4    2234.827957  229.128532     3015.0     1636.0  2152.709677  162.067527   
..           ...         ...        ...        ...          ...         ...   
560  2326.346154  609.009015     4452.0      954.0  1480.423077  485.605425   
561  1504.282258  378.170640     2603.0      289.0  1612.544355  294.738098   
562  2671.226974  682.515132     4039.0      639.0  2771.601974  713.917935   
563  1820.726415  345.413057     2468.0      799.0  1889.198113  331.853071   
564  1501.523691  324.311802     2910.0      950.0  2211.620948  393.738240   

     b5_max_12  b5_min_12  
0       2255.0      622.0  
1       2675.0     1139.0  
2       1892.0     1242.0  
3       2659.0     1228.0  
4       2489.0     1704.0  
..         ...        ...  
560     2512.0      488.0  
561     2641.0      848.0  
562     3923.0      562.0  
563     2685.0     1329.0  
564     3869.0     1387.0  

[565 rows x 348 columns]

In [189]:
X_submit = submit_df.to_numpy()
X_submit_scaled = scaler.transform(X_submit)

In [191]:
Y_submit = eclf1.predict(X_submit_scaled)

np.unique(Y_submit, return_counts=True)

(array([1, 2, 3, 4]), array([252, 109, 149,  55]))

In [192]:
df_submit = pd.DataFrame(Y_submit, columns=['crop_type'])
df_submit.to_csv('ktaff-final_submission.csv')

In [194]:
test_output_df = pd.read_csv('ktaff-final_submission.csv')

In [34]:
test_output_df

Unnamed: 0  crop_type
0             0          2
1             1          2
2             2          4
3             3          2
4             4          1
..          ...        ...
560         560          1
561         561          3
562         562          1
563         563          1
564         564          1

[565 rows x 2 columns]

In [195]:
test_output_df.groupby('crop_type').count()

Unnamed: 0
crop_type            
1                 252
2                 109
3                 149
4                  55